### ISSUE TITLE
`atomic_write` is broken on Windows

### ISSUE THREAD

**Issue by janpio** [segiddins/atomos#5]
I amy trying to run project using `xcodeproj`, which uses `atomos`, on Windows. 
Unfortunately this fails with this error message in `atomic_write`:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:23:in `rename': [!] Permission denied @ rb_file_s_rename - (C:/Users/Jan/AppData/Local/Temp/.atomos.project.pbxproj20180806-12188-1yujbo3, C:/Projects/Fastlane/fastlane-demo/ionic/FastlaneDemoIonic/platforms/ios/FastlaneDemoIonic.xcodeproj/project.pbxproj) (Errno::EACCES)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:23:in `block in atomic_write'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tempfile.rb:295:in `open'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:16:in `atomic_write'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:354:in `save'
        ...
```

Crashing code is triggered here:
https://github.com/CocoaPods/Xcodeproj/blob/c6c0dbb0f977367c32fceea514c372dc9f8ab13f/lib/xcodeproj/project.rb#L354-L362

Crashing code is this:
https://github.com/segiddins/atomos/blob/b3660fce9ab43ff05342a6d2e8633021238a5bcf/lib/atomos.rb#L23

(Original issue for this was at https://github.com/CocoaPods/Xcodeproj/issues/549 - now moved here as I actually have to get this working)

**Comment by janpio** [comment]
Ok, so I found a workaround:

Call `tmpfile.close` before moving the file. 

This StackOverflow answer gave me the idea to test this:
https://stackoverflow.com/a/38360482/252627

PR incoming.
