### ISSUE TITLE
File rename error - macOS Catalina

### ISSUE THREAD

**Issue by AndrewEQ** [segiddins/atomos#7]
Hi there,

I was just running `pod update`, then I got this error:

```
### Error

Errno::EXDEV - Cross-device link @ rb_file_s_rename - (/var/folders/73/qmchj7tx5jv2d2cz2rsx3_yh0000gn/T/.atomos.project.pbxproj20190729-13707-13jqlpy, /MyApp/build/iOS/Debug/Pods/Pods.xcodeproj/project.pbxproj)
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `rename'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.11.0/lib/xcodeproj/project.rb:363:in `save'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:56:in `block (2 levels) in write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:42:in `block in write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:41:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:41:in `write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:313:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/update.rb:62:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

pod file:
```
platform :ios, '9.3'

target 'MyApp' do
	use_frameworks!
	pod 'lottie-ios', '~> 2.5.3'
	pod 'UberRides', '~> 0.11'
end
```

**Comment by AndrewEQ** [comment]
Ok, so I moved my project folder out of the root path (/) and into my user folder, everything worked fine after that. Probably tighter security on Catalina now.
